--建立CASE資料表的結構
CREATE TABLE "CASE" 
   (	"INCIDENT_NUMBER" VARCHAR2(255 BYTE), 
	"OFFENSE_CODE" VARCHAR2(255 BYTE), 
	"OFFENSE_CODE_GROUP" VARCHAR2(255 BYTE), 
	"OFFENSE_DESCRIPTION" VARCHAR2(255 BYTE), 
	"SHOOTING" VARCHAR2(255 BYTE), 
	"OCCURRED_ON_DATE" VARCHAR2(255 BYTE), 
	"YEAR" VARCHAR2(255 BYTE), 
	"MONTH" VARCHAR2(255 BYTE), 
	"DAY_OF_WEEK" VARCHAR2(255 BYTE), 
	"HOUR" VARCHAR2(255 BYTE), 
	"UCR_PART" NUMBER(255 BYTE), 

   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  --建立LOCATION資料表的結構
  REATE TABLE "LOCATION" 
   (	"INCIDENT_NUMBER" VARCHAR2(255 BYTE), 
	"DISTRICT" VARCHAR2(255 BYTE), 
	"REPORTING_AREA" VARCHAR2(255 BYTE), 
	"STREET" VARCHAR2(255 BYTE), 
	"Lat" VARCHAR2(255 BYTE), 
	"Long" VARCHAR2(255 BYTE), 
	"Location" VARCHAR2(255 BYTE), 

   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


  
/*查詢句1：2018年的犯罪案件*/
SELECT *
FROM CASE 
WHERE YEAR="2018"; --未建立索引時成本為1310

--以YEAR建立索引
CREATE INDEX I1 ON CASE(YEAR);

--再次執行查詢
SELECT *
FROM CASE 
WHERE YEAR="2018";--成本下降為950+114




/*查詢句2：在星期天的C11區發生的犯罪案件*/
SELECT *
FROM CASE NATURAL JOIN LOCATION
WHERE DAY_OF_WEEK='Sunday' AND DISTRICT='C11';--成本為1037(LOCATION)和1310(CASE)

--以DAY_OF_WEEK建立索引
CREATE INDEX I2 ON CASE(DAY_OF_WEEK);

--再次執行查詢
SELECT *
FROM CASE NATURAL JOIN LOCATION
WHERE DAY_OF_WEEK='Sunday' AND DISTRICT='C11';--成本並無下降，系統判斷不需使用索引

--強制以索引執行
SELECT /*+ index(CASE (DAY_OF_WEEK))*/*
FROM CASE NATURAL JOIN LOCATION
WHERE DAY_OF_WEEK='Sunday' AND DISTRICT='C11';--成本十分高昂




/*查詢句3：在2017年發生且犯罪類型代碼為301的犯罪案件*/
SELECT *
FROM CASE
WHERE YEAR='2017'
AND OFFENSE_CODE='301';--成本為1309

--以YEAR,OFFENSE_CODE建立索引
CREATE INDEX I3 ON CASE(YEAR, OFFENSE_CODE);

--再次執行查詢
SELECT *
FROM CASE
WHERE YEAR='2017'
AND OFFENSE_CODE='301';--成本降為551+5